### ISSUE TITLE
No exception when name registered without transient

### ISSUE THREAD

**Issue by McBussloo** [yuriy-nelipovich/DependencyInjection.Extensions#10]
If you register a type or object by name, but forget to register it as transient, no exception is thrown but a null object is returned.
I would expect the ServiceByNameFactory to return an invalidoperation exception.

Or maybe AddByName can perform a check earlier in the process?

Examples:

`
            public interface ICommand
            {

            }

            public class FirstCommand : ICommand
            {

            }

            [TestMethod]
            public void MissingTransientByType()
            {
                var serviceCollection = new ServiceCollection();

                const string commandName = "first";
                var firstCommand = typeof(FirstCommand);

//                serviceCollection.AddTransient(firstCommand);

                serviceCollection.AddByName<ICommand>()
                    .Add(commandName, firstCommand).Build();

                var serviceProvider = serviceCollection.BuildServiceProvider();

                var serviceByNameFactory = serviceProvider.GetService<IServiceByNameFactory<ICommand>>();

                var commandInstance = serviceByNameFactory.GetByName(commandName);

                Assert.IsNotNull(commandInstance);
            }

            [TestMethod]
            public void MissingTransientByObject()
            {
                var serviceCollection = new ServiceCollection();

                const string commandName = "first";

                //serviceCollection.AddTransient<FirstCommand>();

                serviceCollection.AddByName<ICommand>()
                    .Add<FirstCommand>(commandName).Build();

                var serviceProvider = serviceCollection.BuildServiceProvider();

                var serviceByNameFactory = serviceProvider.GetService<IServiceByNameFactory<ICommand>>();

                var commandInstance = serviceByNameFactory.GetByName(commandName);

                Assert.IsNotNull(commandInstance);
            }

`

**Comment by kevmoens** [comment]
I read this [(https://github.com/dotnet/runtime/issues/53919)]

It looks like this was added to Microsoft.Extensions.DependencyInjection 6.0.0.  

Looks like GetRequiredService method would throw an exception.  There might be instances where we don't care and have it works like today.

So, I am thinking of adding a new GetByNameRequired method that would solve the problem.  I will work on a PR.

**Comment by nullptre** [comment]
That makes sense, especially due to `ServiceByNameFactory.GetByName()` throws exception when name is unknown. So I will review and add that possibility, with awareness of breaking change.

**Comment by nullptre** [comment]
New version has been published, https://www.nuget.org/packages/Neleus.DependencyInjection.Extensions/1.0.6
