### ISSUE TITLE
Consider publish to NuGet Gallery?

### ISSUE THREAD

**Issue by doggy8088** [yuriy-nelipovich/DependencyInjection.Extensions#12]
Are you consider publish your library to NuGet Gallery?

**Comment by doggy8088** [comment]
I found there is one: [Neleus.DependencyInjection.Extensions](https://www.nuget.org/packages/Neleus.DependencyInjection.Extensions)

I suggest you can put this info on the `README.md`.

**Comment by nullptre** [comment]
Thanks for pointing. Will do when have more free time.

**Comment by doggy8088** [comment]
@yuriy-nelipovich I think you can simply put a link here:
![image](https://user-images.githubusercontent.com/88981/163198772-f2c90148-1bc8-47ec-a534-068200230cbb.png)
