### ISSUE TITLE
New Add/GetByType?

### ISSUE THREAD

**Issue by IndigoHealth** [yuriy-nelipovich/DependencyInjection.Extensions#2]
`ServicesByNameBuilder.Add` requires a name (string) argument.  Later in the workflow, `IServiceByNameFactory.GetByName` materializes the class based on that name.

Assuming that the "name" has no intrinsic meaning (possibly a bad assumption?) it seems to me that, for the name argument to `.Add` I might want to use the `Type` name, and later I would want to use that same `Type` name in `.GetByName`.  For example:

    .Add<MyImplementation>(typeof(MyImplementation).Name)
    …
    _service = factory.GetByName(typeof(MyImplementation).Name);

This scheme allows the "name" to be strongly typed.  So, my question is, is there a reason not to extend this product to support two new methods:

    // Both methods use typeof(T).Name as the "name"
    .Add<T>()
    …
    _service = factory.GetByType<T>()

**Comment by nullptre** [comment]
So why can't you just ask IoC container to resolve the type you need? Like below:

```
MyConstructor(MyImplementation service)
{
    _service = service;
}
```

It looks more natural. Is there any reason against that approach?

**Comment by IndigoHealth** [comment]
Oh, I didn't realize I could do that. I'm still wrapping my brain around the whole DI thing. Thanks!
