### ISSUE TITLE
How to specify AddSingleton?

### ISSUE THREAD

**Issue by dotsad** [yuriy-nelipovich/DependencyInjection.Extensions#3]
How would you add you service to be Singleton?

**Comment by nullptre** [comment]
Do you mean `IServiceByNameFactory` registration? The only benefit of having `IServiceByNameFactory` as Singleton is little performance improvement. Is that the goal?

**Comment by nullptre** [comment]
@dotsad Can you please provide more details about your goal?

**Comment by tranb3r** [comment]
@yuriy-nelipovich 
I think it would be better in terms of performance to register IServiceByNameFactory as Singleton.
Is there any reason not to do it ?
Or could you add an option to do it ?
