### ISSUE TITLE
GetbyName case insensitive

### ISSUE THREAD

**Issue by esakkiraja-k** [yuriy-nelipovich/DependencyInjection.Extensions#5]
Hi,
Could you please make getbyName method to case insensitive.

**Comment by nullptre** [comment]
Hi, currenltly I have no free time however will try to do that soon.

**Comment by esakkiraja-k** [comment]
thanks

**Comment by nullptre** [comment]
@esakkiraja-k please check my last commits. I've added it as optional settings. Nuget package is also available https://www.nuget.org/packages/Neleus.DependencyInjection.Extensions

**Comment by nullptre** [comment]
@esakkiraja-k you can cancel the PR as well

**Comment by esakkiraja-k** [comment]
@yuriy-nelipovich thanks Yuriy.
