### ISSUE TITLE
GetByName<T>(name) -> GetServiceByName<T>(name)

### ISSUE THREAD

**Issue by boexler** [yuriy-nelipovich/DependencyInjection.Extensions#7]
Could you change the extensions method to `GetServiceByName` instead of just `GetByName` ? So as not to break the existing naming convention.

**Comment by nullptre** [comment]
As I can see the standard methods don't have `Service`, like `AddTransient<>` or `AddSingleton<>` so what naming convention do you mean?

**Comment by boexler** [comment]
I mean the `IServiceProvider` extension (https://github.com/yuriy-nelipovich/DependencyInjection.Extensions/blob/master/Neleus.DependencyInjection.Extensions/FactoryServiceCollectionExtensions.cs#L38)

have a look at https://github.com/aspnet/DependencyInjection/blob/master/src/DI.Abstractions/ServiceProviderServiceExtensions.cs#L21


![grafik](https://user-images.githubusercontent.com/17551597/75440678-7f8c8400-595c-11ea-8867-171bb35b46d0.png)

**Comment by nullptre** [comment]
Now I got your point. Will add this method and leave old one for backwards compatibility.
